name: context test
 
on: ['push']

jobs:
  context-test:
    runs-on: ubuntu-latest
    steps:
      - name: "test context"
        run: |
         echo "Triggered by: ${{ github.actor }}"
         echo "Event name: ${{ github.event_name }}"
         echo "Repository: ${{ github.repository }}"
         echo "Branch/Ref: ${{ github.ref }}"
         echo "Workflow name: ${{ github.workflow }}"
      
      - name: "all details in Json"
        run: echo "${{ toJson(github) }}"
