name: webflow commands

on: ['push']

jobs:
  webflow-cmd:
      runs-on: ubuntu-latest 
      step:
         -name: "group messages"
         run: |
          echo: "::group::My group Messages"
          echo: "Messages 1"
          echo: "Messages 2"
          echo: "Messages 3"
          echo: "Messages 4"
          echo: "::endgroup::"
        
